.TH "NPM\-CONFIG" "1" "October 2018" "" ""
.SH "NAME"
\fBnpm-config\fR \- 管理 npm 配置文件
.SH 概述
.P
.RS 2
.nf
npm config set <key> <value> [\-g|\-\-global]
npm config get <key>
npm config delete <key>
npm config list [\-l] [\-\-json]
npm config edit
npm get <key>
npm set <key> <value> [\-g|\-\-global]

别名: c
.fi
.RE
.SH 描述
.P
npm 会从命令行、环境变量、\fBnpmrc\fP 文件、（某些情况下包括）\fBpackage\.json\fP 文件获取配置设置。
.P
关于 \fBnpmrc\fP 文件的更多信息参见 npm help 5 \fBnpmrc\fP。
.P
对有关机制更全面的讨论参见 npm help 7 \fBnpm\-config\fP。
.P
\fBnpm config\fP 命令可以被用于更新、编辑用户和全局的 \fBnpmrc\fP 文件内容。
.SH 子命令
.P
\fBnpm config\fP 支持以下子命令：
.SS set
.P
.RS 2
.nf
npm config set key value
.fi
.RE
.P
将配置 \fBkey\fP 设置为 \fBvalue\fP。
.P
如果省略了 \fBvalue\fP，将会设置为 \fB"true"\fP。
.SS get
.P
.RS 2
.nf
npm config get key
.fi
.RE
.P
输出配置值到标准输出。
.SS list
.P
.RS 2
.nf
npm config list
.fi
.RE
.P
显示所有的配置设置。使用 \fB\-l\fP 会显示所有的默认配置。使用 \fB\-\-json\fP 会以 JSON 格式显示所有配置。
.SS delete
.P
.RS 2
.nf
npm config delete key
.fi
.RE
.P
从所有的配置文件中删除 \fBkey\fP。
.SS edit
.P
.RS 2
.nf
npm config edit
.fi
.RE
.P
在编辑器中打开配置文件。使用 \fB\-\-global\fP 标记来编辑全局配置。
.SH 参见
.RS 0
.IP \(bu 2
npm help 5 folders
.IP \(bu 2
npm help 7 config
.IP \(bu 2
npm help 5 package\.json
.IP \(bu 2
npm help 5 npmrc
.IP \(bu 2
npm help npm

.RE

