.TH "NPM\-STARS" "1" "October 2018" "" ""
.SH "NAME"
\fBnpm-stars\fR \- 查看被标记为喜欢的包
.SH 概述
.P
.RS 2
.nf
npm stars [<user>]
.fi
.RE
.SH 描述
.P
如果你已经给许多包标记星号，并且想要再次快速地找到它们，本命令可以让你做到这一点。
.P
你可能也想看看你朋友喜欢的包，这种情况下，你肯定会喜欢本命令。
.SH 参见
.RS 0
.IP \(bu 2
npm help star
.IP \(bu 2
npm help view
.IP \(bu 2
npm help whoami
.IP \(bu 2
npm help adduser

.RE

