.TH "NPM\-ROOT" "1" "October 2018" "" ""
.SH "NAME"
\fBnpm-root\fR \- 显示 npm 根目录
.SH 概述
.P
.RS 2
.nf
npm root [\-g]
.fi
.RE
.SH 描述
.P
打印有效的 \fBnode_modules\fP 文件夹到标准输出。
.SH 参见
.RS 0
.IP \(bu 2
npm help prefix
.IP \(bu 2
npm help bin
.IP \(bu 2
npm help 5 folders
.IP \(bu 2
npm help config
.IP \(bu 2
npm help 7 config
.IP \(bu 2
npm help 5 npmrc

.RE

