.TH "NPM\-STOP" "1" "October 2018" "" ""
.SH "NAME"
\fBnpm-stop\fR \- 停止包
.SH 概述
.P
.RS 2
.nf
npm stop [\-\- <args>]
.fi
.RE
.SH 描述
.P
执行包的 "stop" 脚本，如果包提供了的话。
.SH 参见
.RS 0
.IP \(bu 2
npm help run\-script
.IP \(bu 2
npm help 7 scripts
.IP \(bu 2
npm help test
.IP \(bu 2
npm help start
.IP \(bu 2
npm help restart

.RE

