.TH "NPM\-DEPRECATE" "1" "October 2018" "" ""
.SH "NAME"
\fBnpm-deprecate\fR \- 将包的某个版本标记为已废弃
.SH 概述
.P
.RS 2
.nf
npm deprecate <pkg>[@<version>] <message>
.fi
.RE
.SH 描述
.P
本命令将会更新包的 npm registry 条目，向所有尝试安装它的人提供一个弃用的警告。
.P
它适用于版本范围和指定版本，所以你可以像下面这样做：
.P
.RS 2
.nf
npm deprecate my\-thing@"< 0\.2\.3" "critical bug fixed in v0\.2\.3"
.fi
.RE
.P
注意，你必须是包的所有者才能标记废弃。参见 \fBowner\fP 和 \fBadduser\fP 帮助主题。
.P
要取消废弃一个包，为 \fBmessage\fP 参数指定一个空字符串（\fB""\fP）。
.SH 参见
.RS 0
.IP \(bu 2
npm help publish
.IP \(bu 2
npm help 7 registry

.RE

