.TH "NPM\-STAR" "1" "October 2018" "" ""
.SH "NAME"
\fBnpm-star\fR \- 标记你喜欢的包
.SH 概述
.P
.RS 2
.nf
npm star [<pkg>\.\.\.]
npm unstar [<pkg>\.\.\.]
.fi
.RE
.SH 描述
.P
给一个包“标记星号”意味着你对它感兴趣。这是一种积极的方式，显示你在关注它。
.P
“取消星号”同样如此，但是正好相反。
.P
它是一个布尔类型的值，反复标记星号没有额外效果。
.SH 参见
.RS 0
.IP \(bu 2
npm help view
.IP \(bu 2
npm help whoami
.IP \(bu 2
npm help adduser

.RE

